
package:
  name: sackmesser
  version: "{{ load_setup_py_data().version }}"

build:
  noarch: python
  script: python setup.py install
  entry_points:
    - rename_trimbits = sackmesser.main:rename_trimbits

source:
  path: ..

requirements:
  build:
    - python 

  run:
    - python
    - rich


test:
  imports:
    - sackmesser

about:
  home: https://github.com/slsdetectorgroup/hdf5maker
  license: MIT
  license_family: MIT
  summary: Python utils for PSD Detector Group detectors
